services:
  codereview:
    image: inttype/codereview:latest   # ë¡œì»¬ ë¹Œë“œê°€ í•„ìš”í•˜ë©´ build: ./codereview ìœ ì§€
    build: ./codereview
    container_name: codereview
    env_file:
      - ./.env
    expose:
      - "8080"                 # ë‚´ë¶€í†µì‹ ë§Œ ì—´ê¸°
    networks:
      - review
    restart: always

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - codereview
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - review
    restart: always

  certbot:
    image: certbot/certbot:latest
    container_name: codereview-certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "trap exit TERM; while :; do
      certbot renew --webroot -w /var/www/certbot --quiet && echo 'ğŸ” certs renewed';
      sleep 12h;
      done"
    networks:
      - review
    restart: unless-stopped

networks:
  review:
    driver: bridge
